dataset=read.csv("athletes.csv")
top_50<-head(dataset,50)
summary(top_50)
par(mfrow=c(2, 2))
hist(top_50$Age, main = "Age Distribution", xlab = "Age")
hist(top_50$Height, main = "Height Distribution", xlab = "Height")
hist(top_50$Weight, main = "Weight Distribution", xlab = "Weight")
boxplot(top_50$Age, main = "Age Box Plot")
par(mfrow=c(2, 2))
boxplot(top_50$Age, main = "Age Box Plot")
boxplot(top_50$Height, main = "Height Box Plot")
boxplot(top_50$Weight, main = "Weight Box Plot")
par(mfrow=c(2, 2))
model <- lm(Weight ~ Age, data = top_50)
plot(top_50$Age, top_50$Height, main = "Age vs. Height", xlab = "Age", ylab = "Height")
abline(lm(top_50$Height ~ top_50$Age), col = "red")
plot(top_50$Age, top_50$Weight, main = "Age vs. Weight", xlab = "Age", ylab = "Weight")
abline(lm(top_50$Weight ~ top_50$Age), col = "blue")
plot(top_50$Height, top_50$Weight, main = "Height vs. Weight", xlab = "Height", ylab = "Weight")
abline(lm(top_50$Weight ~ top_50$Height), col = "green") 
model <- lm(Weight ~ Age, data = top_50)
summary(model)
paste('Amount of missing data: ',sum(is.na(top_50)))
head(top_50)
paste('Number of columns: ',length(top_50))
names(top_50)
str(top_50) #checking the data types
install.packages("psych")
Alibrary(psych)
describe(top_50)
unique(top_50$Height)
unique(top_50$NOC)
unique(top_50$City)
table(top_50$Medal)
table(top_50$Sport)
table(top_50$Games)
table(top_50$Sex)
table(top_50$Event)
model_2 <- lm(Weight ~ Height, data = top_50)
summary(model_2)
model_3<-lm(Age ~ Height, data = top_50)
summary(model_3)
